@startuml
'https://plantuml.com/activity-diagram-beta

start
:Verifica se o token está nas preferências do dispositivo;
if (token está nas preferências) then (não)
:redireciona para a página de login;
:realiza a autenticação;

else (sim)
:atualiza os dados do usuário;

endif
:redireciona para a página do calendário;
stop

@enduml
