@startuml
'https://plantuml.com/activity-diagram-beta

start
:Verifica se o token está nas preferências do dispositivo;
if (token está nas preferências) then (false)
:redireciona para o login page;
:realiza a autenticação;
endif
:redireciona para a página do calendário;
stop

@enduml
