@startuml proxy-auth-sequence

autonumber 1

activate User
    User --> Server: Envia a solicitação do token de criação de conta

activate Server
    Server --> Server: Valida o email fornecido pelo usuário
    Server --> Server: Cria o token para criação de conta
    Server --> OutlookEmailServiceProvider: Envia o token para criação de conta

activate OutlookEmailServiceProvider
    User-->OutlookEmailServiceProvider: Busca o token para criação de conta
deactivate

User-->Server: Envia o token de criação de conta para ser validado

Server-->Server: Valida o token para criação de conta
Server-->User: Envia a resposta
User-->Server: Envia os dados de criação de conta
Server-->Server: Verifica a existência do usuário com o email fornecido
Server-->Server: Cria o usuário
Server--> User: Envia a resposta
@enduml