@startuml proxy-auth-sequence

autonumber 1

activate User
    User --> Server: Sends account creation token request

activate Server
    Server --> Server: Validate the email provided by user
    Server --> Server: Create AccountCreationToken
    Server --> OutlookEmailServiceProvider: Send the account creation token

activate OutlookEmailServiceProvider
    User-->OutlookEmailServiceProvider: Retrieves the account creation token
deactivate

User-->Server: Sends the user account token for validation

Server-->Server: Validates account token received from user
Server-->User: Sends response
User-->Server: Sends user creation data
Server-->Server: Validates user existence
Server-->Server: Creates user
Server--> User: Sends response
@enduml